import { EntitySchema } from '@mikro-orm/core';
import { Trace } from '../entities/Trace.js';
import { Tenant } from '../entities/Tenant.js';
import { Agent } from '../entities/Agent.js';

export const TraceSchema = new EntitySchema<Trace>({
  class: Trace,
  tableName: 'traces',
  properties: {
    id: { type: 'uuid', primary: true },
    tenant: { kind: 'm:1', entity: () => Tenant, fieldName: 'tenant_id' },
    agent: { kind: 'm:1', entity: () => Agent, fieldName: 'agent_id', nullable: true },
    requestId: { type: 'string', columnType: 'varchar(255)', fieldName: 'request_id' },
    model: { type: 'string', columnType: 'varchar(255)' },
    provider: { type: 'string', columnType: 'varchar(100)' },
    endpoint: { type: 'string', columnType: 'varchar(255)' },
    requestBody: { type: 'json', fieldName: 'request_body' },
    requestIv: { type: 'string', columnType: 'varchar(24)', fieldName: 'request_iv', nullable: true },
    responseBody: { type: 'json', fieldName: 'response_body', nullable: true },
    responseIv: { type: 'string', columnType: 'varchar(24)', fieldName: 'response_iv', nullable: true },
    latencyMs: { type: 'integer', fieldName: 'latency_ms', nullable: true },
    ttfbMs: { type: 'integer', fieldName: 'ttfb_ms', nullable: true },
    gatewayOverheadMs: { type: 'integer', fieldName: 'gateway_overhead_ms', nullable: true },
    promptTokens: { type: 'integer', fieldName: 'prompt_tokens', nullable: true },
    completionTokens: { type: 'integer', fieldName: 'completion_tokens', nullable: true },
    totalTokens: { type: 'integer', fieldName: 'total_tokens', nullable: true },
    estimatedCostUsd: { type: 'decimal', fieldName: 'estimated_cost_usd', nullable: true },
    encryptionKeyVersion: { type: 'integer', fieldName: 'encryption_key_version', default: 1 },
    statusCode: { type: 'smallint', fieldName: 'status_code', nullable: true },
    createdAt: { type: 'Date', fieldName: 'created_at' },
    knowledgeBaseId: { type: 'string', columnType: 'uuid', fieldName: 'knowledge_base_id', nullable: true },
    embeddingAgentId: { type: 'string', columnType: 'uuid', fieldName: 'embedding_agent_id', nullable: true },
    ragRetrievalLatencyMs: { type: 'integer', fieldName: 'rag_retrieval_latency_ms', nullable: true },
    embeddingLatencyMs: { type: 'integer', fieldName: 'embedding_latency_ms', nullable: true },
    vectorSearchLatencyMs: { type: 'integer', fieldName: 'vector_search_latency_ms', nullable: true },
    retrievedChunkCount: { type: 'integer', fieldName: 'retrieved_chunk_count', nullable: true },
    topChunkSimilarity: { type: 'decimal', fieldName: 'top_chunk_similarity', nullable: true },
    avgChunkSimilarity: { type: 'decimal', fieldName: 'avg_chunk_similarity', nullable: true },
    contextTokensAdded: { type: 'integer', fieldName: 'context_tokens_added', nullable: true },
    ragOverheadTokens: { type: 'integer', fieldName: 'rag_overhead_tokens', nullable: true },
    ragCostOverheadUsd: { type: 'decimal', fieldName: 'rag_cost_overhead_usd', nullable: true },
    ragStageFailed: { type: 'string', columnType: 'varchar(20)', fieldName: 'rag_stage_failed', nullable: true },
    fallbackToNoRag: { type: 'boolean', fieldName: 'fallback_to_no_rag', nullable: true },
  },
});
